### ISSUE TITLE
Upgrade process for your docker image?

### ISSUE THREAD

**Issue by BCorbett0312** [thomasfa18/node-foundry#2]
I recently found your docker image and it has been awesome.  I am just wondering what the process is to upgrade the foundry version?

**Comment by thomasfa18** [comment]
Hi, you can either just run the internal/inbuilt foundry update tool, or you can download and extract and updated version to the location. You mounted /pkg from.

If doing it manually please make sure to backup your config and don't overwrite your use data (/data)
