### ISSUE TITLE
Ubuntu - Docker Contianer Restart Loop

### ISSUE THREAD

**Issue by N0S1gnal** [thomasfa18/node-foundry#5]
**Resolved**
Docker was already installed via ``snap`` which was causing issues every time I installed Docker via their own recommended method. Removing the ``snap`` installed version of Docker, and re-installing Docker via their own recommended method resolved the issues. (user error indeed)

**Current Behavior**
- Container created by using ``docker compose up`` with the ``example compose`` file on Ubuntu server 24.04.1 LTS throws an error and restarts the container every 60 seconds.
- During those 60 seconds, I'm able to log into the FoundryVTT app and verify everything works up until the container reboots and throws me back to the landing page.

**Expected Behavior**
- image is pulled, Container is created, and app remains accessible without reboot.

 **Trouble Shooting Steps Taken**
- Verified location and permissions of files in ``/pkg`` and ``/data``
-  The file ``/pkg/resources/app/main.js`` exists in the expected location
- Able to successfully launch container on Windows and Synology devices using same compose file
- ``Node.js`` and ``npm`` installed on base system

```
node:internal/modules/cjs/loader:1051
throw err;
^

Error: Cannot find module '/pkg/resources/app/main.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
 }
 
 Node.js v20.7.0
```

[foundry docker error.txt](https://github.com/user-attachments/files/17122537/foundry.docker.error.txt)

[example compose.txt](https://github.com/user-attachments/files/17122538/example.compose.txt)

(apologies in advance as I'm fairly new to Ubuntu - thanks for making the app it's been a great help)

**Comment by thomasfa18** [comment]
Hi @N0S1gnal,
Thanks for taking to time to provide feedback.

I don't currently have an ubuntu machine, but I will spin up a 24.04.1 LTS VM and see if I can replicate the error you are seeing.
Can you please provide which version of docker you are using (eg. docker.io or docker-ce), where your mountpoints are located (eg. local FS, external mounts), and which user context the containers are launching under

From the error message you've posted though it would indicate that the problem is definitely to do with the container mounting the path. Can you please identify which user docker is running under and whether that user:group has permissions to the mount.

**Comment by thomasfa18** [comment]
I've replicated your docker environment based on your compose yaml.
I can't find an issue.

Based on your paths I might assume that they're either external mounts or the user your are running docker as (1000) lacks permissions.

I would suggest launching an interactive container and confirming you can browse to the expected paths.

I will leave this issue open for a few days for a response, if none received then it will eb closed

**Comment by N0S1gnal** [comment]
Thanks for the response and taking a look. Not entirely surprising I managed to muck up the file permissions…

``/volume1`` is a separate internal SATA drive from the OS disk. Permissions ``drwxr-xr-x 4 755 myuser myuser``

``/volume1/docker/foundrystack`` permissions ``drwxrwxrwx 6 755 myuser myuser``

Running ``id`` shows ``UID=1000`` and ``PGID=1000`` and ``1001(docker)``

Docker version 27.3.1, ce12230


Feel free to close the issue (esp. if this can be solved by doing some simple searches)

Thanks again for the help, and at least confirming that I mucked something up 😅

**Comment by thomasfa18** [comment]
If myuser is gid and uid 1000 as per your compose then that should be correct. 
For reference I used user 1000 and chown -R on the foundrystack dir to that user. Running your docker compose encountered no errors.

Suggest running the container interactively and confirming path access.
